# Generated by Django 2.2.6 on 2019-10-09 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('token', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('stopped', 'Stopped')], default=('active', 'Active'), max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('directorName', models.CharField(max_length=100)),
                ('contactDirector', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('stopped', 'Stopped')], default=('active', 'Active'), max_length=12)),
                ('agreementDocNumber', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('maxNumberOfChild', models.SmallIntegerField(blank=True, default=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.School')),
                ('subGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30, verbose_name='Имя')),
                ('middleName', models.CharField(blank=True, max_length=30)),
                ('lastName', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('enteredDate', models.DateField(default=datetime.datetime(2019, 10, 9, 8, 55, 38, 983414, tzinfo=utc))),
                ('father', models.CharField(blank=True, max_length=100)),
                ('contactFather', models.CharField(blank=True, max_length=12)),
                ('mother', models.CharField(blank=True, max_length=100)),
                ('contactMother', models.CharField(blank=True, max_length=12)),
                ('monthlyFee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('agreementNumber', models.CharField(default='', max_length=20)),
                ('birthCertificateNumber', models.CharField(default='', max_length=20)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.School')),
            ],
        ),
    ]
