# Generated by Django 2.2.6 on 2019-11-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='bankAccount',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Счет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='mfo',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='МФО Банка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='taxNumber',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='ИНН'),
            preserve_default=False,
        ),
    ]
