# Generated by Django 2.2.6 on 2019-11-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191102_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='bankAccount',
            field=models.CharField(max_length=20, verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mfo',
            field=models.CharField(max_length=5, verbose_name='МФО Банка'),
        ),
        migrations.AlterField(
            model_name='school',
            name='taxNumber',
            field=models.CharField(max_length=9, verbose_name='ИНН'),
        ),
    ]
