# Generated by Django 2.2.6 on 2019-11-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191110_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'default_permissions': (), 'permissions': (('add_core_group', 'Can add Группа'), ('change_core_group', 'Can change Группа'), ('delete_core_group', 'Can delete Группа'), ('view_core_group', 'Can view Группа')), 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
