# Generated by Django 2.2.6 on 2019-10-09 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paymentTime', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 8, 55, 38, 985753))),
                ('terminal', models.CharField(max_length=32)),
                ('mfo', models.CharField(max_length=5)),
                ('paymentMethod', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default=('online', 'Online'), max_length=12)),
                ('cheque', models.FileField(blank=True, upload_to='cheques')),
                ('appType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.App')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Child')),
            ],
        ),
    ]
