---
- name: "Deploy Project"
  hosts: all
  vars:
    ansistrano_deploy_to: "/var/www/kidspay"
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: git@github.com:Farrukh17/KidsPayAPI.git
    ansistrano_git_branch: master
    ansistrano_keep_releases: 5
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/tasks.yml"
    ansistrano_shared_files: ['KidsPayAPI/local_settings.py']
    ansistrano_allow_anonymous_stats: false

  pre_tasks:
    - name: "Create dirs"
      shell: "mkdir -p /var/www/kidspay/shared/KidsPayAPI"
    - name: "Upload files"
      copy:
        src: "{{ playbook_dir }}/files_{{group_names | first }}/{{ item.src }}"
        dest: "{{ ansistrano_deploy_to }}/shared/{{ item.dest }}"
      with_items:
        - {src: "local_settings.py", dest: "KidsPayAPI/local_settings.py"}
  post_tasks:
    - name: "Changing perm of pg_backup_rotated.sh, adding +x"
        file: "dest=/var/www/kidspay/current/config/backup/pg_backup_rotated.sh mode=a+x"
  roles:
    - {role: ansistrano.deploy}
